### ISSUE TITLE
Getting error sending mail

### ISSUE THREAD

**Issue by jaragones** [OfficeDev/O365-iOS-Unified-API-Connect#10]
I'm getting an error trying to send mail (example). What I did was to add my credentials to the code:

NSString * const kRedirectUri = @"urn:ietf:wg:oauth:2.0:oob";
NSString * const kClientId    = @"2578***c-d343-****-92d1-*********";

and execute, error that I'm getting is (see below). I tried with same clientId into the SDK code and works properly. I wonder if it an issue related to scopes. On SDK example, scopes must be added, and for REST looks that they aren't. If it needs be added can you point me where, please?

2017-01-31 12:47:11.770 O365-iOS-Microsoft-Graph-Connect[90999:3987545] Response - <NSHTTPURLResponse: 0x600000423ee0> { URL: https://graph.microsoft.com/v1.0/me/microsoft.graph.sendmail } { status code: 401, headers {
    "Cache-Control" = private;
    "Content-Type" = "application/json";
    Date = "Tue, 31 Jan 2017 11:47:11 GMT";
    Duration = "4468.1981";
    Server = "Microsoft-IIS/8.5";
    "Transfer-Encoding" = Identity;
    "X-Powered-By" = "ASP.NET";
    "client-request-id" = "1a4b3828-a8b6-4fe7-b826-75d018f8ce40";
    "request-id" = "1a4b3828-a8b6-4fe7-b826-75d018f8ce40";
    "x-ms-ags-diagnostic" = "{\"ServerInfo\":{\"DataCenter\":\"North Europe\",\"Slice\":\"SliceA\",\"ScaleUnit\":\"001\",\"Host\":\"AGSFE_IN_4\",\"ADSiteName\":\"DUB\"}}";
} }

2017-01-31 12:47:11.772 O365-iOS-Microsoft-Graph-Connect[90999:3987545] Received Data - {
  "error": {
    "code": "UnknownError",
    "message": "",
    "innerError": {
      "request-id": "1a4b3828-a8b6-4fe7-b826-75d018f8ce40",
      "date": "2017-01-31T11:47:12"
    }
  }
}

**Comment by jamescro** [comment]
Hello. Unfortunately the client id you're using with the SDK samples won't work with this sample. The SDK sample uses v2.0 auth, which assigns permission scopes dynamically. This sample is still on v1.0 auth, which requires you to go to the Azure Management Portal, create a client, and assign permissions to the client there. The readme points to these instructions for registering this kind of client: https://github.com/microsoftgraph/ios-objectivec-connect-rest-sample/wiki/Grant-permissions-to-the-Connect-application-in-Azure

We'll log a work item for upgrading this sample to v2.0 auth.
