### ISSUE TITLE
MSAL version issue?

### ISSUE THREAD

**Issue by auspicious99** [OfficeDev/O365-iOS-Unified-API-Connect#11]
This sample code comes with its own version of MSAL in Carthage/Checkout, that is a year old, which seems to be different from the latest MSAL that we would otherwise get by following the instructions to use Carthage. For example, this one contains an MSALUser object, but the latest MSAL from Carthage does not. Hence, if we remove the contents of Carthage/Checkout and get the latest MSAL using Carthage, we have compile problems as there is no MSALUser object.

Do you need to update the instructions on here? (don't use Carthage but just use the older MSAL code?). Or need to update the sample code to work with the latest MSAL available from Carthage?

**Comment by ghost** [comment]
Also having this issue, it looks like now there will have to be a call to the Graph api using the Access token in order to get any user information, where previously the user identifying information was returned with the access token.

**Comment by jasonjoh** [comment]
See #12 for a fix.

**Comment by ghost** [comment]
So Cartfile contents just need to be:
 github AzureAD/microsoft-authentication-library-for-objc\" == 0.1.3"

is that correct?

**Comment by jasonjoh** [comment]
I believe so.

**Comment by ghost** [comment]
Nice thanks.

**Comment by auspicious99** [comment]
Works, thanks! Probably better in the long term to update this sample code to keep up with the latest in the MSAL repo, though. Any plans for that?
