### ISSUE TITLE
Need a Swift version.

### ISSUE THREAD

**Issue by James-Parsons** [OfficeDev/O365-iOS-Unified-API-Connect#5]
In fact, the Office developer website says there is a Swift version, but it's not in here.

**Comment by jthake** [comment]
Where do you see the mention of Swift on the Office developer web site?
We are currently not working on a Swift version of the SDK.

**Comment by bmitchell287** [comment]
@James-Parsons - James would you point us to where it mentions the swift version? Currently we just have the obj-c sample available. Thanks.
