### ISSUE TITLE
O365-iOS-Microsoft-Graph-Connect Error: 3072

### ISSUE THREAD

**Issue by krunalbhavsar** [OfficeDev/O365-iOS-Unified-API-Connect#9]
Getting this error:
NSCocoaErrorDomain ProtocolCode:(null) Details:The operation was cancelled.. Inner error details: Error Domain=NSCocoaErrorDomain Code=3072 "The operation was cancelled."

**Comment by jamescro** [comment]
Sorry that it took so long to respond. We haven't been able to reproduce this issue, so I'll close this. Please reopen if this problem persists for you.
